apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishery
  labels:
    app: fishery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fishery
  template:
    metadata:
      labels:
        app: fishery
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: fishery
        image: your-dockerhub-username/fishery:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fishery-service
spec:
  selector:
    app: fishery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
