name: Build, Push and Deploy Microservices
       
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  minikube-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
      
      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Set kubectl context to Minikube
        run: |
          kubectl config use-context minikube       
          
  build-push-deploy:
    runs-on: ubuntu-latest
    needs: minikube-setup
    strategy:
      matrix:
        service:
          - animal-rearing
          - fishery
          - poultry
          - backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./e-farming-project/${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/efarming-${{ matrix.service }}:latest
           
      - name: Create kubeconfig directory
        run: mkdir -p $HOME/.kube && mkdir -p $HOME/.minikube/profiles/minikube

      - name: Decode kubeconfig and certificates
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          echo "${{ secrets.MINIKUBE_CLIENT_CERT }}" | base64 --decode > $HOME/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" | base64 --decode > $HOME/.minikube/profiles/minikube/client.key
          echo "${{ secrets.MINIKUBE_CA_CERT }}" | base64 --decode > $HOME/.minikube/ca.crt      
    

      # Apply Security Configurations
      - name: Apply Security Configurations
        run: |
          kubectl apply -f k8s/security/rbac-role.yml
          kubectl apply -f k8s/security/service-accounts.yml
          kubectl apply -f k8s/security/network-policies.yml

       # Step 8: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/${{ matrix.service }}-deployment ${{ matrix.service }}=${{ secrets.DOCKER_HUB_USERNAME }}/efarming-${{ matrix.service }}:latest

      - name: Verify Deployments
        run: |
          kubectl get pods
          kubectl get services
     
     
